"""Runtime exactness and CUDA publication helpers."""

from .attestation import (
    NO_TRUSTED_ATTESTERS,
    RELEASE_TRUSTED_ATTESTER_POLICY,
    AttestationChallenge,
    SignedAttestation,
    TrustedAttesterPolicy,
    attestation_message,
    require_release_trusted_attester_policy,
    verify_attestation_signature,
)
from .attester_bundle import (
    SOURCE_RELEASE_TRUSTED_ATTESTER_ANCHOR,
    AttestationNoncePolicy,
    LoadedTrustedAttesterPolicyBundle,
    TrustedAttesterAnchorDescriptor,
    TrustedAttesterPolicyBundle,
    TrustedAttesterPolicyBundleBinding,
    load_source_release_trusted_attester_policy_bundle,
    load_trusted_attester_policy_bundle,
)
from .compile_cache import (
    COMPILE_CACHE_ENVIRONMENT_VARIABLES,
    PINNED_SGLANG_COMPILE_SOURCE_SHA256,
    CompileCacheAttemptReceipt,
    CompileCacheCorruptionError,
    CompileCacheFile,
    CompileCacheForeignIdentityError,
    CompileCacheIncompleteError,
    CompileCacheKey,
    CompileCacheLaunchPlan,
    CompileCacheLaunchSession,
    CompileCacheOverlay,
    CompileCacheReceipt,
    ImmutableCompileCache,
    preflight_compile_cache_launch,
    start_compile_cache_launch,
)

__all__ = [
    "COMPILE_CACHE_ENVIRONMENT_VARIABLES",
    "DISTRIBUTED_RUNTIME_SUITE_RUNNER_PROTOCOL_SHA256S",
    "EAGLE3_COMPATIBILITY_PROTOCOL_SHA256",
    "EAGLE3_E0_EXECUTION_PROTOCOL_SHA256",
    "EAGLE3_OFFICIAL_SELECTOR_CONTENT_PROTOCOL_SHA256",
    "EAGLE3_OFFICIAL_SELECTOR_RELATIVE_PATH",
    "NATIVE_RUNTIME_GPU_TEST_FILES",
    "NATIVE_RUNTIME_GPU_TEST_NAMES",
    "NATIVE_RUNTIME_QUALIFICATION_AUTHORITY_SHA256",
    "NATIVE_RUNTIME_QUALIFICATION_PROTOCOL_SHA256",
    "NATIVE_RUNTIME_QUALIFICATION_RUNNER_SHA256",
    "NATIVE_RUNTIME_QUALIFICATION_TESTS",
    "NATIVE_RUNTIME_QUALIFICATION_TEST_SET_SHA256",
    "NATIVE_RUNTIME_RELEASE_CAPABILITY",
    "NATIVE_RUNTIME_SUITE_CAPABILITIES",
    "NATIVE_RUNTIME_SUITE_RUNNER_PROTOCOL_SHA256S",
    "NEXTN_TP2_DYNAMIC_AUTHORITY_PROTOCOL_SHA256",
    "NO_TRUSTED_ATTESTERS",
    "PINNED_SGLANG_COMPILE_SOURCE_SHA256",
    "RELEASE_TRUSTED_ATTESTER_POLICY",
    "SESSION_RESET_GPU_TEST_FILE",
    "SESSION_RESET_GPU_TEST_NAMES",
    "SESSION_RESET_RUNNER_PROTOCOL_SHA256",
    "SOURCE_RELEASE_TRUSTED_ATTESTER_ANCHOR",
    "AdaptationCollectiveMode",
    "AllRankPublicationCoordinator",
    "AttestationChallenge",
    "AttestationNoncePolicy",
    "BackendContract",
    "BackendNotApplicable",
    "BackendPayload",
    "BackendRegistry",
    "CanvasReconstruction",
    "CohortRouteIdentity",
    "CompileCacheAttemptReceipt",
    "CompileCacheCorruptionError",
    "CompileCacheFile",
    "CompileCacheForeignIdentityError",
    "CompileCacheIncompleteError",
    "CompileCacheKey",
    "CompileCacheLaunchPlan",
    "CompileCacheLaunchSession",
    "CompileCacheOverlay",
    "CompileCacheReceipt",
    "ContentVerificationReceipt",
    "CudaPublicationCoordinator",
    "DFlashBackendContract",
    "DSparkBackendContract",
    "DSparkSelectorAuthority",
    "DifferentiableCanvasContract",
    "DistributedControlMode",
    "DistributedRuntimeAuthorityBlocked",
    "DistributedRuntimeGpuProofArtifact",
    "DistributedRuntimeGpuProofReceipt",
    "DistributedRuntimeReleaseCapability",
    "Eagle3CompatibilityAuthority",
    "Eagle3OfficialSelectorManifest",
    "Eagle3OfficialSelectorRow",
    "EagleBackendContract",
    "FunctionalBackendContract",
    "GlooPublicationTransport",
    "GraphFixedAddressContract",
    "GraphHotPathReceipt",
    "GraphHotPathStateMachine",
    "GraphTensorBinding",
    "ImmutableCompileCache",
    "InferenceParameterOwnership",
    "LoadedTrustedAttesterPolicyBundle",
    "NativeItlBufferBinding",
    "NativeItlResultPointer",
    "NativeItlTimestampStateMachine",
    "NativeReadinessBlocked",
    "NativeRuntimeGpuProofArtifact",
    "NativeRuntimeGpuProofReceipt",
    "NativeRuntimeQualificationAssignment",
    "NativeRuntimeQualificationDispatchAuthority",
    "NativeRuntimeQualificationError",
    "NativeRuntimeQualificationFailurePointer",
    "NativeRuntimeQualificationObservation",
    "NativeRuntimeQualificationResultPointer",
    "NativeRuntimeReleaseCapability",
    "NativeTokenTimestampEvent",
    "NextNBackendContract",
    "NextNTp2DynamicAuthorityArtifact",
    "NextNTwoModelTp2Authority",
    "ParameterOwnership",
    "PrepareDisposition",
    "PreparedPublication",
    "ProposalEvidence",
    "PublicationCandidate",
    "PublicationDecision",
    "PublicationOutcome",
    "RankDecisionReceipt",
    "RankPrepare",
    "RankTopologyReceipt",
    "Reconstruction",
    "ReplicaLocalRouter",
    "RuntimeTopologyMode",
    "SessionResetDispatchAuthority",
    "SessionResetQualificationAssignment",
    "SessionResetQualificationFailurePointer",
    "SessionResetQualificationProofPointer",
    "SessionResetQualificationResultPointer",
    "SessionResetRawRankTerminal",
    "SignedAttestation",
    "TopologyIdentity",
    "TopologyReceiptSet",
    "TrustedAttesterAnchorDescriptor",
    "TrustedAttesterPolicy",
    "TrustedAttesterPolicyBundle",
    "TrustedAttesterPolicyBundleBinding",
    "UpdateIdentity",
    "VerifiedDistributedRuntimeGpuProof",
    "VerifiedEagle3CompatibilityAuthority",
    "VerifiedEagle3E0ExecutionAuthority",
    "VerifiedEagle3OfficialSelectorContentAuthority",
    "VerifiedNativeRuntimeGpuProof",
    "VerifiedNextNTp2Authority",
    "adaptation_collective_mode",
    "attestation_message",
    "authorize_native_runtime_qualification_dispatch",
    "authorize_session_reset_dispatch",
    "bind_eagle3_e0_execution_authority",
    "build_distributed_runtime_gpu_proof_artifact",
    "build_native_runtime_gpu_proof_artifact",
    "derive_stage_content_verification_receipt",
    "distributed_control_mode",
    "dspark_composite_loss",
    "dspark_conditional_survival_target",
    "execute_native_runtime_qualification",
    "execute_session_reset_qualification",
    "finalize_native_runtime_qualification",
    "finalize_session_reset_qualification",
    "load_source_release_trusted_attester_policy_bundle",
    "load_trusted_attester_policy_bundle",
    "nextn_snapshot_shard_manifest_sha256",
    "nextn_tp2_dynamic_proof_sha256",
    "position_weighted_kl",
    "preflight_compile_cache_launch",
    "publish_nextn_tp2_dynamic_authority_artifact",
    "registered_runtime_topology_mode",
    "rejection_sample",
    "require_chronobelief_gpu_proof",
    "require_distributed_runtime_release_capability",
    "require_eagle3_e0_execution_authority",
    "require_fixed_address_graph_gpu_proof",
    "require_release_nextn_tp2_authority",
    "require_release_trusted_attester_policy",
    "resolve_eagle3_official_selector_content_authority",
    "start_compile_cache_launch",
    "validate_decision_receipts",
    "validate_distributed_runtime_gpu_proof_artifact",
    "validate_native_runtime_gpu_proof_artifact",
    "validate_nextn_tp2_dynamic_authority_artifact",
    "verify_attestation_signature",
    "verify_distributed_runtime_gpu_proof",
    "verify_eagle3_compatibility_authority",
    "verify_formal_eagle3_compatibility_authority",
    "verify_native_runtime_gpu_proof",
]


def __getattr__(name: str) -> object:
    backend_exports = {
        "BackendContract",
        "BackendNotApplicable",
        "BackendPayload",
        "BackendRegistry",
        "DFlashBackendContract",
        "DSparkBackendContract",
        "DSparkSelectorAuthority",
        "EAGLE3_COMPATIBILITY_PROTOCOL_SHA256",
        "EAGLE3_E0_EXECUTION_PROTOCOL_SHA256",
        "EAGLE3_OFFICIAL_SELECTOR_CONTENT_PROTOCOL_SHA256",
        "EAGLE3_OFFICIAL_SELECTOR_RELATIVE_PATH",
        "EagleBackendContract",
        "Eagle3CompatibilityAuthority",
        "Eagle3OfficialSelectorManifest",
        "Eagle3OfficialSelectorRow",
        "FunctionalBackendContract",
        "NEXTN_TP2_DYNAMIC_AUTHORITY_PROTOCOL_SHA256",
        "NextNBackendContract",
        "NextNTp2DynamicAuthorityArtifact",
        "NextNTwoModelTp2Authority",
        "ProposalEvidence",
        "Reconstruction",
        "VerifiedEagle3CompatibilityAuthority",
        "VerifiedEagle3E0ExecutionAuthority",
        "VerifiedEagle3OfficialSelectorContentAuthority",
        "VerifiedNextNTp2Authority",
        "dspark_composite_loss",
        "dspark_conditional_survival_target",
        "bind_eagle3_e0_execution_authority",
        "nextn_snapshot_shard_manifest_sha256",
        "nextn_tp2_dynamic_proof_sha256",
        "publish_nextn_tp2_dynamic_authority_artifact",
        "require_eagle3_e0_execution_authority",
        "resolve_eagle3_official_selector_content_authority",
        "require_release_nextn_tp2_authority",
        "validate_nextn_tp2_dynamic_authority_artifact",
        "verify_eagle3_compatibility_authority",
        "verify_formal_eagle3_compatibility_authority",
    }
    canvas_exports = {
        "CanvasReconstruction",
        "DifferentiableCanvasContract",
        "position_weighted_kl",
    }
    content_authorization_exports = {
        "ContentVerificationReceipt",
        "derive_stage_content_verification_receipt",
    }
    distributed_exports = {
        "AdaptationCollectiveMode",
        "AllRankPublicationCoordinator",
        "CohortRouteIdentity",
        "DistributedControlMode",
        "DistributedRuntimeAuthorityBlocked",
        "DistributedRuntimeGpuProofArtifact",
        "DistributedRuntimeGpuProofReceipt",
        "DistributedRuntimeReleaseCapability",
        "DISTRIBUTED_RUNTIME_SUITE_RUNNER_PROTOCOL_SHA256S",
        "GlooPublicationTransport",
        "InferenceParameterOwnership",
        "ParameterOwnership",
        "PrepareDisposition",
        "PreparedPublication",
        "PublicationCandidate",
        "PublicationDecision",
        "PublicationOutcome",
        "RankDecisionReceipt",
        "RankPrepare",
        "RankTopologyReceipt",
        "ReplicaLocalRouter",
        "TopologyIdentity",
        "TopologyReceiptSet",
        "RuntimeTopologyMode",
        "UpdateIdentity",
        "VerifiedDistributedRuntimeGpuProof",
        "adaptation_collective_mode",
        "build_distributed_runtime_gpu_proof_artifact",
        "distributed_control_mode",
        "validate_decision_receipts",
        "validate_distributed_runtime_gpu_proof_artifact",
        "verify_distributed_runtime_gpu_proof",
        "registered_runtime_topology_mode",
        "require_distributed_runtime_release_capability",
    }
    readiness_exports = {
        "GraphFixedAddressContract",
        "GraphHotPathReceipt",
        "GraphHotPathStateMachine",
        "GraphTensorBinding",
        "NativeItlBufferBinding",
        "NativeItlResultPointer",
        "NativeItlTimestampStateMachine",
        "NativeReadinessBlocked",
        "NativeRuntimeGpuProofArtifact",
        "NativeRuntimeGpuProofReceipt",
        "NativeRuntimeReleaseCapability",
        "NativeTokenTimestampEvent",
        "NATIVE_RUNTIME_QUALIFICATION_AUTHORITY_SHA256",
        "NATIVE_RUNTIME_QUALIFICATION_PROTOCOL_SHA256",
        "NATIVE_RUNTIME_QUALIFICATION_RUNNER_SHA256",
        "NATIVE_RUNTIME_QUALIFICATION_TESTS",
        "NATIVE_RUNTIME_QUALIFICATION_TEST_SET_SHA256",
        "NATIVE_RUNTIME_RELEASE_CAPABILITY",
        "NATIVE_RUNTIME_SUITE_CAPABILITIES",
        "NATIVE_RUNTIME_SUITE_RUNNER_PROTOCOL_SHA256S",
        "VerifiedNativeRuntimeGpuProof",
        "build_native_runtime_gpu_proof_artifact",
        "require_fixed_address_graph_gpu_proof",
        "require_chronobelief_gpu_proof",
        "validate_native_runtime_gpu_proof_artifact",
        "verify_native_runtime_gpu_proof",
    }
    native_qualification_exports = {
        "NATIVE_RUNTIME_GPU_TEST_FILES",
        "NATIVE_RUNTIME_GPU_TEST_NAMES",
        "NativeRuntimeQualificationAssignment",
        "NativeRuntimeQualificationDispatchAuthority",
        "NativeRuntimeQualificationError",
        "NativeRuntimeQualificationFailurePointer",
        "NativeRuntimeQualificationObservation",
        "NativeRuntimeQualificationResultPointer",
        "authorize_native_runtime_qualification_dispatch",
        "execute_native_runtime_qualification",
        "finalize_native_runtime_qualification",
    }
    session_reset_exports = {
        "SESSION_RESET_GPU_TEST_FILE",
        "SESSION_RESET_GPU_TEST_NAMES",
        "SESSION_RESET_RUNNER_PROTOCOL_SHA256",
        "SessionResetDispatchAuthority",
        "SessionResetQualificationAssignment",
        "SessionResetQualificationFailurePointer",
        "SessionResetQualificationProofPointer",
        "SessionResetQualificationResultPointer",
        "SessionResetRawRankTerminal",
        "authorize_session_reset_dispatch",
        "execute_session_reset_qualification",
        "finalize_session_reset_qualification",
    }
    if name in backend_exports:
        from . import backend

        return getattr(backend, name)
    if name in canvas_exports:
        from . import dflash_canvas

        return getattr(dflash_canvas, name)
    if name in content_authorization_exports:
        from . import content_authorization

        return getattr(content_authorization, name)
    if name in distributed_exports:
        from . import distributed

        return getattr(distributed, name)
    if name in readiness_exports:
        from . import readiness

        return getattr(readiness, name)
    if name in native_qualification_exports:
        from . import native_qualification_runner

        return getattr(native_qualification_runner, name)
    if name in session_reset_exports:
        from . import session_reset_runner

        return getattr(session_reset_runner, name)
    if name == "rejection_sample":
        from .exactness import rejection_sample

        return rejection_sample
    if name == "CudaPublicationCoordinator":
        from .publication import CudaPublicationCoordinator

        return CudaPublicationCoordinator
    raise AttributeError(name)
