"""GPU-resident cohort adaptation primitives."""

from .cohort import CohortIdentity, CohortRuntime, SupervisionSignal
from .governor import (
    BoundedCohortStateManager,
    CohortAdmission,
    CohortAdmissionReason,
    CohortOffloadMode,
    CohortReclamationReceipt,
    CohortStateKey,
    CohortStateSnapshot,
    CohortTransferReceipt,
    HBMAdmission,
    HBMAdmissionReason,
    HBMAdmissionRequest,
    HBMGovernor,
    HBMLedger,
    MemoryPressureAction,
    MemoryPressureStep,
    RankHeadroom,
    RankMemoryState,
)
from .kv_history import FrozenKVHistory, KVSegment
from .memory import AdaptationMemoryLedger
from .optimizer import FixedAddressBank, GPUOptimizer
from .parameters import (
    DSPARK_HYBRID_SCOPES,
    LAYER_SCOPES,
    LORA_RANKS,
    TRAINABLE_PLAN_OPTIMIZERS,
    TRAINABLE_PLAN_REDUCER_PROTOCOL_SHA256,
    DFlashParameterPlan,
    DSparkParameterPlan,
    LoRAFactors,
    NativeLayerParameterPlan,
    TrainablePlan,
)
from .plan_authority import (
    DSparkNativeHeadNames,
    E1RecipeAnchorTrainablePlanSemantics,
    PreparedDrafterParameterInventory,
    PreparedParameterMetadata,
    TrainablePlanAuthorityBinding,
    TrainablePlanAuthorityResult,
    TrainablePlanRawJsonBinding,
    TtsCalibrationTrainablePlanSemantics,
    audit_trainable_plan_authority_for_method,
    bind_trainable_plan_authority,
    build_e1_recipe_anchor_trainable_plan_semantics,
    build_tts_calibration_trainable_plan_semantics,
    materialize_trainable_plan_authority_manifest,
    replay_trainable_plan_authority,
    require_trainable_plan_authority_for_method,
    trainable_plan_authority_binding_from_dict,
    trainable_plan_authority_binding_to_dict,
    trainable_plan_cell_source_to_dict,
)

__all__ = [
    "DSPARK_HYBRID_SCOPES",
    "LAYER_SCOPES",
    "LORA_RANKS",
    "TRAINABLE_PLAN_OPTIMIZERS",
    "TRAINABLE_PLAN_REDUCER_PROTOCOL_SHA256",
    "AdaptationMemoryLedger",
    "BoundedCohortStateManager",
    "CohortAdmission",
    "CohortAdmissionReason",
    "CohortIdentity",
    "CohortOffloadMode",
    "CohortReclamationReceipt",
    "CohortRuntime",
    "CohortStateKey",
    "CohortStateSnapshot",
    "CohortTransferReceipt",
    "DFlashParameterPlan",
    "DSparkNativeHeadNames",
    "DSparkParameterPlan",
    "E1RecipeAnchorTrainablePlanSemantics",
    "FixedAddressBank",
    "FrozenKVHistory",
    "GPUOptimizer",
    "HBMAdmission",
    "HBMAdmissionReason",
    "HBMAdmissionRequest",
    "HBMGovernor",
    "HBMLedger",
    "KVSegment",
    "LoRAFactors",
    "MemoryPressureAction",
    "MemoryPressureStep",
    "NativeLayerParameterPlan",
    "PreparedDrafterParameterInventory",
    "PreparedParameterMetadata",
    "RankHeadroom",
    "RankMemoryState",
    "SupervisionSignal",
    "TrainablePlan",
    "TrainablePlanAuthorityBinding",
    "TrainablePlanAuthorityResult",
    "TrainablePlanRawJsonBinding",
    "TtsCalibrationTrainablePlanSemantics",
    "audit_trainable_plan_authority_for_method",
    "bind_trainable_plan_authority",
    "build_e1_recipe_anchor_trainable_plan_semantics",
    "build_tts_calibration_trainable_plan_semantics",
    "materialize_trainable_plan_authority_manifest",
    "replay_trainable_plan_authority",
    "require_trainable_plan_authority_for_method",
    "trainable_plan_authority_binding_from_dict",
    "trainable_plan_authority_binding_to_dict",
    "trainable_plan_cell_source_to_dict",
]
